# Generated by Django 5.2.8 on 2025-11-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
