# Generated by Django 5.2.8 on 2025-12-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stafflogmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflogmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='stafflogmodel',
            name='affected_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='affected_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stafflogmodel',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stafflogmodel',
            name='field_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stafflogmodel',
            name='new_value',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='stafflogmodel',
            name='old_value',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
