# Generated by Django 5.2.8 on 2025-12-11 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminalertmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminalertmodel',
            options={'verbose_name': 'Admin Alert', 'verbose_name_plural': 'Admin Alerts'},
        ),
        migrations.AlterField(
            model_name='adminalertmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
