# Generated by Django 5.2.8 on 2025-12-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_adminalertmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminalertmodel',
            name='for_staff',
            field=models.BooleanField(default=False),
        ),
    ]
