# Generated by Django 5.2.8 on 2025-11-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0005_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('ml', 'Millilitre'), ('l', 'Litre'), ('pack', 'Pack')], max_length=10, null=True),
        ),
    ]
