# Generated by Django 5.2.8 on 2025-11-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0006_productmodel_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
