# Generated by Django 5.2.8 on 2025-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0007_productmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='unit',
            field=models.CharField(choices=[('kg', 'kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('ml', 'Millilitre'), ('l', 'Litre'), ('pack', 'Pack')], max_length=10),
        ),
    ]
