# Generated by Django 5.2.8 on 2025-11-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0009_sellermodel'),
    ]

    operations = []
