# Generated by Django 5.2.8 on 2025-11-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0011_alter_productmodel_seller'),
    ]

    operations = []
