# Generated by Django 5.2.8 on 2025-11-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0012_remove_productmodel_seller'),
    ]

    operations = []
