# Generated by Django 5.2.8 on 2025-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0013_rename_seller_sellermodel_name'),
    ]

    operations = []
