# Generated by Django 5.2.8 on 2025-11-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0014_delete_sellermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerModel',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='seller',
        ),
    ]
