# Generated by Django 5.2.8 on 2025-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0017_productmodel_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='weight_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
