# Generated by Django 5.2.8 on 2025-11-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0019_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
