# Generated by Django 5.2.8 on 2025-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0021_ordermodel_orderitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
