# Generated by Django 5.2.8 on 2025-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0023_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
