# Generated by Django 5.2.8 on 2025-11-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0025_alter_ordermodel_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Nexto.paymentmodel'),
        ),
    ]
