# Generated by Django 5.2.8 on 2025-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0027_paymentmodel_address_paymentmodel_handling_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='total',
        ),
    ]
