# Generated by Django 5.2.8 on 2025-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0028_remove_paymentmodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
