# Generated by Django 5.2.8 on 2025-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0029_alter_paymentmodel_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='return_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
