# Generated by Django 5.2.8 on 2025-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0030_alter_ordermodel_return_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
