# Generated by Django 5.2.8 on 2025-12-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0031_ordermodel_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='Nexto.paymentmodel'),
        ),
    ]
