# Generated by Django 5.2.8 on 2025-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0032_alter_ordermodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='return_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
