# Generated by Django 5.2.8 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0033_orderitemmodel_return_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
