# Generated by Django 5.2.8 on 2025-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0034_orderitemmodel_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
