# Generated by Django 5.2.8 on 2025-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0035_alter_orderitemmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='return_till',
            field=models.DateField(),
        ),
    ]
