# Generated by Django 5.2.8 on 2025-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0036_alter_orderitemmodel_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='return_window_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='return_window_value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
