# Generated by Django 5.2.8 on 2025-12-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0037_categorymodel_return_window_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='return_till',
            field=models.DateTimeField(),
        ),
    ]
