# Generated by Django 5.2.8 on 2025-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0038_alter_orderitemmodel_return_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='return_window_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='return_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
