# Generated by Django 5.2.8 on 2025-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0039_alter_categorymodel_return_window_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='return_window_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10, null=True),
        ),
    ]
