# Generated by Django 5.2.8 on 2025-12-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0041_shippingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='placed', max_length=40),
        ),
        migrations.CreateModel(
            name='OrderStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Nexto.ordermodel')),
            ],
            options={
                'verbose_name': 'Orderstatus',
                'verbose_name_plural': 'Orderstatus',
            },
        ),
    ]
