# Generated by Django 5.2.8 on 2025-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0042_alter_ordermodel_order_status_orderstatusmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='placed', max_length=40),
        ),
        migrations.DeleteModel(
            name='OrderStatusModel',
        ),
    ]
