# Generated by Django 5.2.8 on 2025-12-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0045_orderstatusmodel_update_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatusmodel',
            old_name='update_by',
            new_name='updated_by',
        ),
    ]
