# Generated by Django 5.2.8 on 2025-12-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0046_rename_update_by_orderstatusmodel_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='delivery_window_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='delivery_window_value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
