# Generated by Django 5.2.8 on 2025-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexto', '0047_categorymodel_delivery_window_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
